apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: scale-test-app-sm
  namespace: default
  labels:
    serviceMonitorSelector: prometheus

spec:
  endpoints:
    - targetPort: 8080
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: scale-test-app     
